logger: 
  default: warn
  logs:
    custom_components.browser_mod: error
    custom_components.pyscript: info
    custom_components.tapo: error
    custom_components.xiaomi_miot: critical
    androidtv: critical
    plugp100.api.tapo_client: error
    pychromecast.socket_client: critical
    homeassistant: error
    homeassistant.core: error
    homeassistant.components: error
    homeassistant.helpers: error
    homeassistant.loader: error
    homeassistant.setup: error
    homeassistant.const: error
  filters:
    homeassistant:
      - "Error doing job: Future exception was never retrieved" # TADO 
      - "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))" # TADO
      - "not been tested by Home Assistant"
    custom_components.hacs:
      - "https://api.github.com/rate_limit"
    homeassistant.components.google_assistant.http:
      - "404"
      - "500"
    homeassistant.components.websocket_api.http.connection: 
      - "io.robbie.HomeAssistant"
    aiohttp.server: 
      - "Error handling request"

logbook: 
  exclude:
    entity_globs: 
      - "*.*browser_mod*"

system_log:
  max_entries: 5
  fire_event: true